import { Notice, Benefit, Coupon, CoexEvent, CommunityPost, ParkingInfo, ContactDept, Poll } from '../types';

export const mockNotices: Notice[] = [
  {
    id: '1',
    title: '[공사] GITC 공사 관련 이동 동선 안내',
    category: 'construction',
    content: 'GITC 공사로 인해 B1층 통행로가 변경됩니다. 정문 우측 임시 통로를 이용해 주시기 바랍니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-24',
    endDate: '2026-06-30',
    isUrgent: false,
    contactPhone: '02-6000-1234',
    createdAt: '2026-04-24',
  },
  {
    id: '2',
    title: '[운영] 주차장 이용 안내',
    category: 'operations',
    content: '코엑스몰 행사 기간 동안 주차 혼잡이 예상됩니다. 대중교통 이용을 권장합니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-20',
    endDate: '2026-04-30',
    isUrgent: false,
    contactPhone: '02-6000-5678',
    createdAt: '2026-04-20',
  },
  {
    id: '3',
    title: '[긴급] 엘리베이터 A동 3호기 점검 안내',
    category: 'urgent',
    content: 'A동 3호기 엘리베이터가 긴급 점검으로 인해 4시간 운행이 중단됩니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-24',
    endDate: '2026-04-24',
    isUrgent: true,
    contactPhone: '02-6000-9999',
    createdAt: '2026-04-24',
  },
  {
    id: '4',
    title: '[점검] 냉난방 설비 정기점검 안내',
    category: 'construction',
    content: '5월 정기 냉난방 설비 점검이 진행됩니다. 점검 시간 동안 일부 층 냉난방이 중단됩니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-05-10',
    endDate: '2026-05-10',
    isUrgent: false,
    contactPhone: '02-6000-1111',
    createdAt: '2026-04-22',
  },
];

export const mockBenefits: Benefit[] = [
  {
    id: '1',
    title: '여름 해피아워 골프 프로모션 (최대 60% 할인)',
    brandName: 'TGX 골프 아카데미',
    category: 'leisure',
    description: '타석 정기권, 무기명·횟수 쿠폰, 해피아워, 개인 레슨까지 7월 한정 특가로 제공하는 골프 연습 프로모션입니다.',
    discountText: '최대 60% 할인',
    location: '코엑스몰 B2 · TGX 골프 아카데미',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '9호선 봉은사역 7번 출구 또는 2호선 삼성역 6번 출구로 코엑스몰 진입 후 B2 TGX 아카데미 방문 (문의 02-6490-9455)',
    notes: '타석·정기권 990,000원(7개월, -55%) · 무기명쿠폰 480,000원(-20%) · 횟수쿠폰 250,000원(-28%) · 해피아워 140,000원(-60%, AM9~11·PM2~4) · 개인레슨 442,000원(8회)/832,000원(16회)',
  },
  {
    id: '2',
    title: '입주사 임직원 할인 프로그램',
    brandName: '스타필드 코엑스몰',
    category: 'shopping',
    description: '레스토랑·카페부터 패션·잡화까지 스타필드 코엑스몰 제휴 매장 전체에서 입주사 임직원 할인을 제공합니다.',
    discountText: '최대 20% 할인',
    location: '스타필드 코엑스몰 제휴매장 (광화문석갈비·아그라·캘리포니아피자키친·PF창스·더타코부스·ebt·플랜튜드·제주오존뽁·UFC스포츠·8seconds 등)',
    startDate: '2026-07-06',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '결제 전 사원증 또는 명함 제시',
    notes: '매장별 세트메뉴·음주류 할인 제외 가능. 상세 매장 목록은 starfield.co.kr/coexmall/eventBenefit/events 참고',
  },
  {
    id: '3',
    title: '임직원 영화 관람 할인 + 코엑스지점 전용 관람권',
    brandName: '메가박스 코엑스점',
    category: 'leisure',
    description: 'LED관·리클라이너관 임직원 할인 요금과, 5매+초대권 1매로 구성된 코엑스지점 전용 관람권을 제공합니다.',
    discountText: 'LED관 12,000원 · 리클라이너 13,000원',
    location: '메가박스 코엑스점 현장 매표소',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '현장 매표소에서 사원증·신분증 확인 후 할인 적용',
    notes: '전용 관람권 55,000원(5매+초대권1매, 구매월 포함 3개월 유효·익일부터 사용·환불 불가). 조조·심야·문화의날 등 타 할인 중복 불가, 돌비시네마·MX4D·더부티크 제외, 본인+동반 1인까지. 단체(20인↑)·대관 문의 02-3147-3863~4 / m.megacoex@partner.megabox.co.kr',
  },
  {
    id: '4',
    title: '본인 + 동반 1인 30% 할인',
    brandName: '코엑스 아쿠아리움',
    category: 'leisure',
    description: '아셈타워·트레이드타워 입주사 임직원과 동반 1인 모두에게 동일하게 적용되는 입장 할인입니다.',
    discountText: '30% 할인 (35,000원 → 24,500원)',
    location: '코엑스 아쿠아리움 현장 매표소',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '현장 매표소에서 명함 또는 사원증 지참',
    notes: '아셈타워·트레이드타워 입주사 한정, 본인 포함 동반 1인까지 동일 할인 적용',
  },
  {
    id: '5',
    title: '짐 보관 1+1 · 인천공항 배송 할인',
    brandName: 'GOODLUGG (굿럭)',
    category: 'service',
    description: '별마당 도서관 지하 2층에서 이용하는 짐 보관·공항 배송 서비스를 임직원 전용가로 이용할 수 있습니다.',
    discountText: '짐보관 1+1 · 배송 최대 10% 할인',
    location: '별마당 도서관 지하 2층',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '굿럭 앱/웹(goodlugg.com) 결제 시 할인 코드 입력, 짐보관은 현장에서 사원증 확인 후 적용',
    notes: '짐보관 1+1(사원증 확인) · 인천공항 배송 1만원 할인 코드 GOODLUGG10K · 해외 호텔-공항/교통약자 배송 10% 할인 코드 GOODLUGG10OFF (도쿄·오사카·싱가폴 등 18개 아시아 도시+LA). 카카오톡 문의 pf.kakao.com/_AxoCxeC',
  },
  {
    id: '6',
    title: '입주사 10% 할인',
    brandName: '보노보노 삼성점',
    category: 'fnb',
    description: '아셈타워·트레이드타워 입주사 한정 이자카야 할인, 단체 예약과 무제한 음료도 함께 제공합니다.',
    discountText: '10% 할인',
    location: '보노보노 삼성점',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '현장에서 명함 또는 사원증 지참 (예약 02-3288-8080)',
    notes: '아셈타워·트레이드타워 입주사 한정, 10~70인 단체 가능(빔프로젝터 협의), 와인·막걸리·생맥주 무제한',
  },
  {
    id: '7',
    title: '식사금액 10% 할인 + 군만두 무료제공',
    brandName: '도원 스타일 (현대백화점 무역센터점 10층)',
    category: 'fnb',
    description: '트레이드타워·아셈타워 입주사 임직원 대상 중식당 할인 및 서비스 메뉴 제공.',
    discountText: '10% 할인 (주류 포함)',
    location: '현대백화점 무역센터점 10층',
    startDate: '2026-06-16',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '명함 제시 시 할인 적용',
    notes: '식사금액 10% 할인(주류 포함) + 군만두 무료제공, 타 할인과 중복 적용 불가, 별도 종료 시까지 운영',
  },
  {
    id: '8',
    title: '이탈리안 레스토랑 런치·디너 최대 30% 할인',
    brandName: '파크 하얏트 서울 코너스톤',
    category: 'hotel',
    description: '사전예약 및 선결제가 필요한 호텔 이탈리안 레스토랑의 런치·디너 코스 할인입니다.',
    discountText: '20~30% 할인',
    location: '파크 하얏트 서울 2층 · 이탈리안 레스토랑 코너스톤',
    startDate: '2026-01-01',
    endDate: '2026-08-30',
    imageUrl: '',
    isActive: true,
    usageMethod: 'QR코드 온라인 사전예약 및 선결제 필수, 8인 이상은 유선 예약(02-2016-1235) 시 30% 할인',
    notes: '런치 코스(월~금 11:30~14:30) 20% 할인, 디너 코스(매일 18:00~22:00) 20% 할인, 8인 이상 예약 시 30% 할인 및 프라이빗룸 제공',
  },
  {
    id: '9',
    title: '입주사 전용 스페셜관 최대 88% 할인 (17개 상품)',
    brandName: '안국건강',
    category: 'shopping',
    description: '트레이드타워 입주사 전용으로 운영되는 건강기능식품 스페셜관으로, 7월 한 달간 지정 상품을 특가에 구매할 수 있습니다.',
    discountText: '최대 88% 할인',
    location: '온라인 (AGmall 스페셜관)',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    imageUrl: '',
    isActive: true,
    usageMethod: 'AGmall 회원가입 → 입주사 등록 게시판에 기업명·연락처·명함 첨부 → 등급 변경 후 마이AG에서 입주사 할인코너 입장 (스페셜관 https://s.godo.kr/39vpe)',
    notes: '첫 가입 시 비타민C/D 1,000원 체험 구매 가능, 등급 신청 후 7월 한 달간 혜택상품 외 전상품 5% 추가 할인. 지정 17개 상품은 쿠폰·마일리지 적용 불가, ID당 10개 구매 제한',
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'c1',
    title: 'TGX 골프 아카데미 해피아워 특가 쿠폰',
    benefitId: '1',
    brandName: 'TGX 골프 아카데미',
    code: 'WTC-TGX-2026-001',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    status: 'available',
    downloadedAt: '2026-07-05',
  },
  {
    id: 'c2',
    title: 'GOODLUGG 인천공항 배송 1만원 할인 쿠폰',
    benefitId: '5',
    brandName: 'GOODLUGG (굿럭)',
    code: 'GOODLUGG10K',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'expired',
    downloadedAt: '2026-04-01',
  },
];

export const mockCoexEvents: CoexEvent[] = [
  {
    id: 'e1',
    title: '2026 서울 국제 도서전',
    startDate: '2026-04-20',
    endDate: '2026-04-28',
    location: 'COEX A홀',
    category: '도서/문화',
    imageUrl: '',
    description: '국내외 출판사 600여 개사가 참가하는 국제 도서 전시회',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: true,
  },
  {
    id: 'e2',
    title: '2026 스마트팩토리·자동화산업전',
    startDate: '2026-04-22',
    endDate: '2026-04-25',
    location: 'COEX B홀',
    category: '산업/기술',
    imageUrl: '',
    description: '스마트 제조 및 자동화 관련 최신 기술과 솔루션을 한자리에서',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: false,
  },
  {
    id: 'e3',
    title: '2026 서울 푸드테크 위크',
    startDate: '2026-05-01',
    endDate: '2026-05-04',
    location: 'COEX C홀',
    category: '식품/외식',
    imageUrl: '',
    description: '푸드테크 혁신 기업들의 솔루션과 미래 식품 트렌드 전시',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: true,
  },
  {
    id: 'e4',
    title: '2026 반려동물 박람회',
    startDate: '2026-05-10',
    endDate: '2026-05-12',
    location: 'COEX D홀',
    category: '반려동물',
    imageUrl: '',
    description: '국내 최대 규모 반려동물 전시회',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: false,
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'p1',
    userId: 'u1',
    authorName: '김채용',
    companyName: '(주)테크스타트',
    category: 'recruitment',
    title: '[채용] 프론트엔드 개발자 모집합니다',
    content: '저희 회사에서 React/TypeScript 기반 프론트엔드 개발자를 모집합니다. 경력 2년 이상, 입주사 직원 우대합니다.',
    status: 'published',
    viewCount: 142,
    commentCount: 8,
    contact: '010-2345-6789',
    email: 'hr@techstart.co.kr',
    createdAt: '2026-04-23',
  },
  {
    id: 'p2',
    userId: 'u2',
    authorName: '이나눔',
    companyName: '(주)글로벌컨설팅',
    category: 'secondhand',
    title: '[무료나눔] 사무용 의자 5개 드립니다',
    content: '사무실 이전으로 인해 사무용 의자 5개를 무료로 드립니다. 상태 양호. 직접 가져가실 분 연락주세요.',
    status: 'published',
    viewCount: 89,
    commentCount: 12,
    contact: '010-3456-7890',
    createdAt: '2026-04-22',
  },
  {
    id: 'p3',
    userId: 'u3',
    authorName: '박행사',
    companyName: '(주)이벤트플러스',
    category: 'event',
    title: '[세미나] AI 트렌드 2026 세미나 개최 안내',
    content: '5월 15일 오후 2시, WTC 지하 회의실에서 AI 트렌드 2026 세미나를 개최합니다. 입주사 직원 무료 참가.',
    status: 'published',
    viewCount: 203,
    commentCount: 15,
    link: 'https://event.example.com',
    createdAt: '2026-04-21',
  },
];

export const mockParkingInfo: ParkingInfo = {
  parkingName: 'WTC SEOUL 주차장',
  status: 'busy',
  updatedAt: '2026-04-24T09:30:00',
};

export const mockContacts: ContactDept[] = [
  { id: 'd1', name: '대표 고객센터', phone: '02-6000-0114', icon: 'headset' },
  { id: 'd2', name: '시설 문의', phone: '02-6000-1111', icon: 'build' },
  { id: 'd3', name: '주차 문의', phone: '02-6000-2222', icon: 'local-parking' },
  { id: 'd4', name: '냉난방 문의', phone: '02-6000-3333', icon: 'ac-unit' },
  { id: 'd5', name: '방문자 신청 문의', phone: '02-6000-4444', icon: 'person-add' },
  { id: 'd6', name: '공사/작업 문의', phone: '02-6000-5555', icon: 'construction' },
  { id: 'd7', name: '분실물 문의', phone: '02-6000-6666', icon: 'search' },
];

export const mockPolls: Poll[] = [
  {
    id: 'poll1',
    title: 'GITC 공사 관련 불편사항 조사',
    description:
      '현재 진행 중인 GITC 공사로 인한 불편사항을 파악하여 개선 대책을 마련하고자 합니다. 솔직한 의견을 부탁드립니다.',
    category: '시설/공사',
    startDate: '2026-04-20',
    endDate: '2026-05-10',
    isAnonymous: true,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 87,
    status: 'ongoing',
    createdAt: '2026-04-20',
    questions: [
      {
        id: 'q1',
        text: '공사로 인해 가장 불편한 점은 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '소음 문제', voteCount: 32 },
          { id: 'o2', text: '통행 동선 변경', voteCount: 28 },
          { id: 'o3', text: '주차 공간 감소', voteCount: 18 },
          { id: 'o4', text: '먼지/분진 발생', voteCount: 9 },
        ],
      },
      {
        id: 'q2',
        text: '공사 관련 불편 사항을 주로 언제 겪으시나요? (복수 선택 가능)',
        type: 'multiple',
        required: true,
        options: [
          { id: 'o5', text: '출근 시간대 (오전 8~10시)', voteCount: 41 },
          { id: 'o6', text: '점심 시간대 (오전 12~14시)', voteCount: 25 },
          { id: 'o7', text: '퇴근 시간대 (오후 17~19시)', voteCount: 38 },
          { id: 'o8', text: '종일 불편함', voteCount: 15 },
        ],
      },
      {
        id: 'q3',
        text: '현재 공사 관련 공지 및 안내가 충분하다고 생각하시나요?',
        type: 'rating',
        required: true,
      },
      {
        id: 'q4',
        text: '추가로 개선되었으면 하는 사항이 있으시면 자유롭게 작성해 주세요.',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'poll2',
    title: 'WTC 멤버십 혜택 선호도 조사',
    description:
      '입주사 직원분들이 가장 원하는 멤버십 혜택이 무엇인지 파악하여 혜택을 강화하고자 합니다.',
    category: '멤버십',
    startDate: '2026-04-15',
    endDate: '2026-04-30',
    isAnonymous: false,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 142,
    status: 'ongoing',
    createdAt: '2026-04-15',
    questions: [
      {
        id: 'q1',
        text: '현재 WTC 멤버십 혜택에 얼마나 만족하시나요?',
        type: 'score',
        required: true,
        minScore: 1,
        maxScore: 5,
      },
      {
        id: 'q2',
        text: '가장 자주 이용하는 혜택 카테고리는 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: 'F&B (식음료) 할인', voteCount: 58 },
          { id: 'o2', text: '쇼핑 할인', voteCount: 31 },
          { id: 'o3', text: '호텔 우대', voteCount: 24 },
          { id: 'o4', text: '코엑스 전시/문화', voteCount: 29 },
        ],
      },
      {
        id: 'q3',
        text: '앞으로 추가되었으면 하는 혜택을 선택해 주세요. (복수 선택 가능)',
        type: 'multiple',
        required: true,
        options: [
          { id: 'o5', text: '헬스장/피트니스 할인', voteCount: 73 },
          { id: 'o6', text: '세탁/케어 서비스 할인', voteCount: 44 },
          { id: 'o7', text: '병원/의원 우대', voteCount: 56 },
          { id: 'o8', text: '편의시설 (세차, 세탁) 할인', voteCount: 38 },
          { id: 'o9', text: '온라인 쇼핑 제휴 할인', voteCount: 61 },
        ],
      },
    ],
  },
  {
    id: 'poll3',
    title: 'WTC Membership 앱 기능 만족도 조사',
    description: '앱을 사용해 보신 소감을 알려주세요. 여러분의 의견이 앱을 더 좋게 만듭니다.',
    category: '앱 서비스',
    startDate: '2026-04-24',
    endDate: '2026-05-24',
    isAnonymous: true,
    allowMultiple: false,
    showResults: false,
    totalParticipants: 23,
    status: 'ongoing',
    createdAt: '2026-04-24',
    questions: [
      {
        id: 'q1',
        text: '전반적인 앱 사용 경험은 어떠셨나요?',
        type: 'rating',
        required: true,
      },
      {
        id: 'q2',
        text: '가장 유용한 기능은 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '공지사항 확인', voteCount: 8 },
          { id: 'o2', text: '멤버십 혜택 조회', voteCount: 7 },
          { id: 'o3', text: '신청 메뉴', voteCount: 4 },
          { id: 'o4', text: '코엑스 전시 일정', voteCount: 4 },
        ],
      },
      {
        id: 'q3',
        text: '개선이 필요한 점이나 추가하고 싶은 기능을 알려주세요.',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'poll4',
    title: '주차 이용 만족도 조사',
    description: '코엑스 행사 기간 주차 이용에 관한 만족도를 조사합니다.',
    category: '시설/주차',
    startDate: '2026-04-01',
    endDate: '2026-04-20',
    isAnonymous: true,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 210,
    status: 'ended',
    createdAt: '2026-04-01',
    questions: [
      {
        id: 'q1',
        text: '주차 이용 전반적인 만족도는?',
        type: 'score',
        required: true,
        minScore: 1,
        maxScore: 5,
      },
      {
        id: 'q2',
        text: '주차 혼잡 시 가장 불편한 점은?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '입차 대기 시간 과다', voteCount: 89 },
          { id: 'o2', text: '자리 찾기 어려움', voteCount: 67 },
          { id: 'o3', text: '안내 표지 부족', voteCount: 35 },
          { id: 'o4', text: '출차 시간 지연', voteCount: 19 },
        ],
      },
    ],
  },
];
